name: Build docker systemd img
on:
  watch:
    types: [started]

  workflow_dispatch:

jobs:
  build:
    name: Build Kernel by ${{ github.actor }}
    runs-on: ubuntu-22.04-arm
    if: github.event.repository.owner.id == github.event.sender.id
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"
      CI: "false"
    steps:
    - name: Set swap to 10G
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 10

    - name: Setup build kernel environment
      run: |
        echo "BUILD_TIME=$(TZ=Asia/Shanghai date "+%Y%m%d%H%M")" >> $GITHUB_ENV
        sudo apt-get update
        mkdir -p $GITHUB_WORKSPACE/kernel_workspace

  

    - name: builder docker imges
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace
        git clone https://github.com/tomxi1997/docker-systemd.git
        cd docker-systemd
        source ./env.conf
        cat $GITHUB_ENV
        #docker buildx build -t builder -o type=docker .
        docker build -t docker-systemd:${DISTR}-${VERSION} -f ${DISTR}/${VERSION}.Dockerfile .
    
        
    - name: docker list and save docker img
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace/docker-systemd
        source ./env.conf
        docker save -o docker-systemd-${DISTR}-${VERSION}.tar docker-systemd:${DISTR}-${VERSION}
        chmod +x save.sh
        #./save.sh
  

    - name: Upload docker img
      uses: actions/upload-artifact@v4
      with:
        path: kernel_workspace/docker-systemd/*.tar

  
